//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBK.Web.Api {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NBK.Web.Api.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;AccountTypes&gt;
        ///  &lt;item key=&quot;CA&quot; country=&quot;JO&quot;&gt;Current Account&lt;/item&gt;
        ///  &lt;item key=&quot;CB&quot; country=&quot;JO&quot;&gt;Current Account - Interest Bearing&lt;/item&gt;
        ///  &lt;item key=&quot;CJ&quot; country=&quot;JO&quot;&gt;Credit Card&lt;/item&gt;
        ///  &lt;item key=&quot;CK&quot; country=&quot;JO&quot;&gt;Credit Card Due&lt;/item&gt;
        ///  &lt;item key=&quot;EE&quot; country=&quot;JO&quot;&gt;Fixed Deposit&lt;/item&gt;
        ///  &lt;item key=&quot;CE&quot; country=&quot;JO&quot;&gt;Overdrawn Account&lt;/item&gt;
        ///  &lt;item key=&quot;EA&quot; country=&quot;JO&quot;&gt;Saving Account&lt;/item&gt;
        ///  &lt;item key=&quot;EC&quot; country=&quot;JO&quot;&gt;Staff Salary Account&lt;/item&gt;
        ///  &lt;it [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AccountTypes {
            get {
                return ResourceManager.GetString("AccountTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;DefaultCurrency&gt;
        ///  &lt;item key=&quot;JO&quot;&gt;JOD&lt;/item&gt;
        ///  &lt;item key=&quot;BH&quot;&gt;BHD&lt;/item&gt;
        ///  &lt;item key=&quot;AE&quot;&gt;AED&lt;/item&gt;
        ///&lt;/DefaultCurrency&gt;
        ///.
        /// </summary>
        internal static string DefaultCurrency {
            get {
                return ResourceManager.GetString("DefaultCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;TransactionCodes&gt;
        ///  &lt;item code=&quot;010&quot; country=&quot;JO&quot;&gt;A/C Debit&lt;/item&gt;
        ///  &lt;item code=&quot;015&quot; country=&quot;JO&quot;&gt;Cheque Deposit&lt;/item&gt;
        ///  &lt;item code=&quot;018&quot; country=&quot;JO&quot;&gt;Outport Contra&lt;/item&gt;
        ///  &lt;item code=&quot;020&quot; country=&quot;JO&quot;&gt;Transfer - Debit&lt;/item&gt;
        ///  &lt;item code=&quot;030&quot; country=&quot;JO&quot;&gt;Debit Standing Order&lt;/item&gt;
        ///  &lt;item code=&quot;039&quot; country=&quot;JO&quot;&gt;Cash Withdrawal&lt;/item&gt;
        ///  &lt;item code=&quot;040&quot; country=&quot;JO&quot;&gt;Cash In&lt;/item&gt;
        ///  &lt;item code=&quot;041&quot; country=&quot;JO&quot;&gt;Currency Notes Bought&lt;/item&gt;
        ///  &lt;item [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransactionCodes {
            get {
                return ResourceManager.GetString("TransactionCodes", resourceCulture);
            }
        }
    }
}
