//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Nullable<long> CustomerID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string PigeonHole { get; set; }
        public string VPStaff { get; set; }
        public string PostalCode { get; set; }
        public string Area { get; set; }
        public string LanguageCode { get; set; }
        public string AddressTypeCode { get; set; }
        public string BlockNumber { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string CountryCode { get; set; }
        public string POBox { get; set; }
        public string FloorNumber { get; set; }
        public string UnitNumber { get; set; }
        public string AddressCategory { get; set; }
        public string BuildingPlot { get; set; }
        public string Street { get; set; }
        public string UnitTypeCode { get; set; }
        public string AvenueNo { get; set; }
        public System.DateTime UpdateDateTime { get; set; }
        public int UpdateUserID { get; set; }
        public int AddressID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual AddressExtendedInfo AddressExtendedInfo { get; set; }
    }
}
