//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Addresses = new HashSet<Address>();
            this.Phones = new HashSet<Phone>();
        }
    
        public string CustomerNumber { get; set; }
        public Nullable<System.DateTime> AdditionalDocRequestDate { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string CBKCustomerSubTypeCode { get; set; }
        public string CBKCustomerTypeCode { get; set; }
        public string CBKGroupCode { get; set; }
        public string CentralBankNumber { get; set; }
        public string ChanmberOfCommerce { get; set; }
        public string CivilID { get; set; }
        public Nullable<System.DateTime> CompanyEstablishDate { get; set; }
        public string CountryOfBirth { get; set; }
        public string CountryOriginCode { get; set; }
        public string CurrentMarketingSegmenrCode { get; set; }
        public string CustomerGroup { get; set; }
        public Nullable<int> CustomerIncomeRangeID { get; set; }
        public Nullable<int> CustomerIncomeTypeID { get; set; }
        public Nullable<int> CustomerProfileType { get; set; }
        public string CustomerSummaryInfo { get; set; }
        public string CustPrefAgreementName { get; set; }
        public string DRFIND { get; set; }
        public string EducationCode { get; set; }
        public string Email { get; set; }
        public string EmergencyContactName { get; set; }
        public string EmergencyContactNumber { get; set; }
        public string EmployeeTierID { get; set; }
        public string EmployerCode { get; set; }
        public string EmployerIDNUmber { get; set; }
        public string FamilyFundApplicationNo { get; set; }
        public string FamilyFundApplicationStatus { get; set; }
        public string FirmNumber { get; set; }
        public string FullNameArabic { get; set; }
        public string RefinedFullNameArabic { get; set; }
        public string FullNameEnglish { get; set; }
        public string GenderCode { get; set; }
        public string GeographicsStructureID { get; set; }
        public string IndustryClassID { get; set; }
        public string KCCRefNumber { get; set; }
        public Nullable<System.DateTime> LastKYCDate { get; set; }
        public Nullable<decimal> LastTransferSalaryAmount { get; set; }
        public string LoyalityID { get; set; }
        public string MailReferenceID { get; set; }
        public string MailToAddressTypeCode { get; set; }
        public string ManagementStructureID { get; set; }
        public string MaritalStatusCode { get; set; }
        public string NationalityCode { get; set; }
        public Nullable<int> NumberOfChildren { get; set; }
        public string OccupationCode { get; set; }
        public Nullable<decimal> OtherAssets { get; set; }
        public string OtherNationality { get; set; }
        public string OtherNationality1 { get; set; }
        public string OtherNationality2 { get; set; }
        public string OtherNationality3 { get; set; }
        public Nullable<System.DateTime> PackageEstablishDate { get; set; }
        public Nullable<System.DateTime> PackageLastUpdateDate { get; set; }
        public string PackageTypeCode { get; set; }
        public Nullable<int> PercentRevenue { get; set; }
        public string PoliticalExposeType { get; set; }
        public string PrefDeclaredAddressTypeCode { get; set; }
        public string ProspectMarketingSegmentCode { get; set; }
        public Nullable<System.DateTime> ProspectMarketingSegmentUpdate { get; set; }
        public string Quoted { get; set; }
        public string RecalcitrantFlag { get; set; }
        public string ReferrerID { get; set; }
        public string RelativePoliticalExposeTypeID { get; set; }
        public string RelativePoliticalName { get; set; }
        public Nullable<System.DateTime> RequestDateForAdditionalInfo { get; set; }
        public string ResidencyStatusCode { get; set; }
        public string RiskRating { get; set; }
        public string RiskRatingCode { get; set; }
        public string Role_PositionCode { get; set; }
        public Nullable<long> SalaryAccountNumber { get; set; }
        public Nullable<decimal> SalaryAmount { get; set; }
        public string SalaryRangeCode { get; set; }
        public string ShortName { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string URLAddress { get; set; }
        public string USOwnershipTenPercentOrMore { get; set; }
        public Nullable<decimal> ValueOfAssets { get; set; }
        public string WBBENEWaiverStatus { get; set; }
        public string IDTypeCode { get; set; }
        public string IDNumber { get; set; }
        public string IDNationalityCode { get; set; }
        public Nullable<System.DateTime> IDExpiryDate { get; set; }
        public string FatcaStatus { get; set; }
        public string AdditionalDocCollected { get; set; }
        public string ClassificationQuestion1 { get; set; }
        public string ClassificationQuestion2 { get; set; }
        public string ClassificationQuestion3 { get; set; }
        public string ClassificationQuestion4 { get; set; }
        public Nullable<System.DateTime> RecalcitrantDate { get; set; }
        public string WithHoldingCertificate { get; set; }
        public string EntityCategoryType { get; set; }
        public Nullable<bool> StudentAllowance { get; set; }
        public string CollegeName { get; set; }
        public Nullable<System.DateTime> GraduationDate { get; set; }
        public string SchoolType { get; set; }
        public string FirstJobberFlag { get; set; }
        public string AnnualTurnOver { get; set; }
        public string DCRNumber { get; set; }
        public string LegalReason { get; set; }
        public System.DateTime UpdateDateTime { get; set; }
        public int UpdateUserID { get; set; }
        public long CustomerID { get; set; }
        public Nullable<System.DateTime> LastSalaryTransferDate { get; set; }
        public string AllowanceFirmNumber { get; set; }
        public Nullable<decimal> AllowanceAmount { get; set; }
        public Nullable<System.DateTime> AllowanceLastTransferDate { get; set; }
        public Nullable<bool> BalanceProtector { get; set; }
        public string CBNStatus { get; set; }
        public Nullable<System.DateTime> CBNDate { get; set; }
        public Nullable<int> IndustrialCode { get; set; }
        public string StockExchName { get; set; }
        public string RegisNumber { get; set; }
        public string SponsorEntity { get; set; }
        public string NBKCustomerType { get; set; }
        public string CustomerStatus { get; set; }
        public Nullable<int> PrimaryOfficer { get; set; }
        public string BranchNumber { get; set; }
        public string ChargeExemptionProfileCode { get; set; }
        public string TaxFileIndicator { get; set; }
        public string CustomerGroupClassCode { get; set; }
        public Nullable<int> BusinessSectorCode { get; set; }
        public string CustomerSegmentCode { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> AccountHolderIndicator { get; set; }
        public string DPSAllowedIndicator { get; set; }
        public string LanguageCode { get; set; }
        public string CorporateGroupCode { get; set; }
        public string Title { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Address> Addresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phone> Phones { get; set; }
    }
}
