//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public long CustomerID { get; set; }
        public string PhoneExtendedInfo { get; set; }
        public string PhoneNumber { get; set; }
        public string PhoneTypeID { get; set; }
        public string PhoneCountryCode { get; set; }
        public System.DateTime UpdateDateTime { get; set; }
        public int UpdateUserID { get; set; }
        public int PhoneID { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
