//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBK.Web.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignLead_History
    {
        public System.Guid LeadID { get; set; }
        public int CampaignID { get; set; }
        public short LeadType { get; set; }
        public short ChannelID { get; set; }
        public string Channel { get; set; }
        public string BranchNo { get; set; }
        public string CustomerNo { get; set; }
        public string CustomerName { get; set; }
        public short Status { get; set; }
        public string AdminID { get; set; }
        public string DistributorID { get; set; }
        public string ExecutorID { get; set; }
        public Nullable<System.DateTime> AssignDate { get; set; }
        public Nullable<short> Contacted { get; set; }
        public Nullable<short> Closed { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public string TeamName { get; set; }
    }
}
