//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBK.Web.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignContact
    {
        public int UniqueID { get; set; }
        public int CampaignID { get; set; }
        public System.Guid ContactDefinitionID { get; set; }
    
        public virtual Campaign Campaign { get; set; }
    }
}
