//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBK.Web.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactDefinition
    {
        public short ContactItemID { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<int> ParentID { get; set; }
        public int CloseLeadFlag { get; set; }
        public Nullable<int> Active { get; set; }
        public string LeadTypeID { get; set; }
    }
}
