//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBK.Web.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact_History
    {
        public System.Guid ContactID { get; set; }
        public string CustomerNo { get; set; }
        public string CustomerName { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public System.DateTime ContactDate { get; set; }
        public string ContactType { get; set; }
        public string LeadSource { get; set; }
        public Nullable<System.Guid> LeadID { get; set; }
        public Nullable<short> LeadType { get; set; }
        public Nullable<short> Level1 { get; set; }
        public Nullable<short> Level2 { get; set; }
        public Nullable<short> Level3 { get; set; }
        public string Description { get; set; }
    }
}
