//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBK.Web.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndividualCustomer_History
    {
        public System.Guid LeadID { get; set; }
        public string CustomerNo { get; set; }
        public string EnglishName1 { get; set; }
        public string IDNumber { get; set; }
        public string IDType { get; set; }
        public string OpenBranch { get; set; }
        public string BranchName { get; set; }
        public string Nationality { get; set; }
        public Nullable<int> Age { get; set; }
        public string Sex { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Phone3 { get; set; }
        public string Phone4 { get; set; }
        public string DateOpen { get; set; }
        public string SellerID { get; set; }
        public string SalarySellerID { get; set; }
        public Nullable<double> SalaryAmount { get; set; }
        public string SalaryRange { get; set; }
        public string LastSalaryDt { get; set; }
        public string SalaryTransfer { get; set; }
        public string MarketingSegment { get; set; }
        public string Package { get; set; }
        public string Firm { get; set; }
        public string FirmName { get; set; }
        public Nullable<double> AvailableLimitAmt { get; set; }
        public Nullable<double> AvailableDBR { get; set; }
        public Nullable<double> CreditCardUtilization { get; set; }
        public string CustomerType { get; set; }
        public string CustomerOfficer { get; set; }
        public string AvgBenchMarkRevenue { get; set; }
        public string BenchMarkCost { get; set; }
        public string Profitability { get; set; }
        public string Profitable { get; set; }
        public string PotentialVal { get; set; }
        public string PotentialToGrow { get; set; }
        public string ExtremeValue { get; set; }
        public string IsCustomerWithWOL { get; set; }
        public string IsCustomerWithMobileB { get; set; }
        public string HasPOS { get; set; }
        public string ProcessSalary { get; set; }
        public string NumberOfEmployees { get; set; }
        public string TotalDeposit6Month { get; set; }
        public string CountDeposits6Months { get; set; }
        public string CreditCardType { get; set; }
        public string CreditCardNo { get; set; }
        public string SuggestedCard { get; set; }
        public string Area { get; set; }
        public string Zone { get; set; }
    }
}
