//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBK.Web.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstantLeadChannel
    {
        public int ID { get; set; }
        public int TypeID { get; set; }
        public short ChannelID { get; set; }
        public string Teams { get; set; }
    
        public virtual InstantLeadType InstantLeadType { get; set; }
    }
}
