//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBK.Web.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstantLeadType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InstantLeadType()
        {
            this.InstantLeadChannels = new HashSet<InstantLeadChannel>();
            this.InstantLeadFields = new HashSet<InstantLeadField>();
            this.InstantLeadMaps = new HashSet<InstantLeadMap>();
            this.InstantLeadTransferChannels = new HashSet<InstantLeadTransferChannel>();
        }
    
        public int TypeID { get; set; }
        public string Name { get; set; }
        public short NotificationFlag { get; set; }
        public Nullable<int> SLA { get; set; }
        public Nullable<short> AllowTransfer { get; set; }
        public Nullable<int> AllowBulkLoad { get; set; }
        public Nullable<int> CustomOutcome { get; set; }
        public Nullable<int> CustomOutcomeType { get; set; }
        public Nullable<int> SurveyID { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<int> ShowInCRM { get; set; }
        public Nullable<int> NASFlag { get; set; }
        public Nullable<int> ComposedFlag { get; set; }
        public string MappingQuestion { get; set; }
        public Nullable<int> ChildFlag { get; set; }
        public Nullable<int> SharedFlag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstantLeadChannel> InstantLeadChannels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstantLeadField> InstantLeadFields { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstantLeadMap> InstantLeadMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstantLeadTransferChannel> InstantLeadTransferChannels { get; set; }
    }
}
