//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBK.Web.Api.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LMSEntities : DbContext
    {
        public LMSEntities()
            : base("name=LMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<AreaBranch> AreaBranches { get; set; }
        public virtual DbSet<AreaManager> AreaManagers { get; set; }
        public virtual DbSet<Campaign> Campaigns { get; set; }
        public virtual DbSet<CampaignContact> CampaignContacts { get; set; }
        public virtual DbSet<CampaignLead_History> CampaignLead_History { get; set; }
        public virtual DbSet<Channel> Channels { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Contact_History> Contact_History { get; set; }
        public virtual DbSet<ContactDefinition> ContactDefinitions { get; set; }
        public virtual DbSet<EmailExclusionList> EmailExclusionLists { get; set; }
        public virtual DbSet<FunctionRole> FunctionRoles { get; set; }
        public virtual DbSet<FunctionRoleDef> FunctionRoleDefs { get; set; }
        public virtual DbSet<IndividualCustomer> IndividualCustomers { get; set; }
        public virtual DbSet<IndividualCustomer_History> IndividualCustomer_History { get; set; }
        public virtual DbSet<InstantLead> InstantLeads { get; set; }
        public virtual DbSet<InstantLead_History> InstantLead_History { get; set; }
        public virtual DbSet<InstantLeadChannel> InstantLeadChannels { get; set; }
        public virtual DbSet<InstantLeadData> InstantLeadDatas { get; set; }
        public virtual DbSet<InstantLeadData_History> InstantLeadData_History { get; set; }
        public virtual DbSet<InstantLeadField> InstantLeadFields { get; set; }
        public virtual DbSet<InstantLeadMap> InstantLeadMaps { get; set; }
        public virtual DbSet<InstantLeadNASRole> InstantLeadNASRoles { get; set; }
        public virtual DbSet<InstantLeadTransferChannel> InstantLeadTransferChannels { get; set; }
        public virtual DbSet<InstantLeadType> InstantLeadTypes { get; set; }
        public virtual DbSet<LeadTransferHistory> LeadTransferHistories { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Survey> Surveys { get; set; }
        public virtual DbSet<SurveyAnswer> SurveyAnswers { get; set; }
        public virtual DbSet<SurveyAnswer_History> SurveyAnswer_History { get; set; }
        public virtual DbSet<SurveyQuestion> SurveyQuestions { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<TeamMember> TeamMembers { get; set; }
        public virtual DbSet<CampaignLead> CampaignLeads { get; set; }
    }
}
