//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBK.Web.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public System.Guid NotificationID { get; set; }
        public string UserID { get; set; }
        public short Type { get; set; }
        public string NotificationText { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
