//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBK.Web.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamMember
    {
        public System.Guid TeamMemberID { get; set; }
        public short TeamID { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public short TeamLeader { get; set; }
        public string PartyId { get; set; }
    
        public virtual Team Team { get; set; }
    }
}
