//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBK.Web.CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAccessLog
    {
        public string CustomerNo { get; set; }
        public string CustomerName { get; set; }
        public string UserID { get; set; }
        public System.DateTime DateTime { get; set; }
        public string ProfileType { get; set; }
    }
}
